### ISSUE TITLE
Testing with spring MocMVC

### ISSUE THREAD

**Issue by nidomiro** [graphql-java-kickstart/graphql-spring-boot#230] opened 2019-04-05 18:36 UTC
I want to test graphql and integrate it into my REST-Spring-Boot-Application.
Currently I'm getting errors because all my tests are using MocMVC, but as I found out, this graphql lib needs a real Servlet, not the MocMvc one.

```
Caused by: java.lang.UnsupportedOperationException: MockServerContainer does not support addEndpoint(ServerEndpointConfig)
	at org.springframework.test.context.web.socket.MockServerContainer.addEndpoint(MockServerContainer.java:131)
	at org.springframework.web.socket.server.standard.ServerEndpointExporter.registerEndpoint(ServerEndpointExporter.java:169)
	at org.springframework.web.socket.server.standard.ServerEndpointExporter.registerEndpoints(ServerEndpointExporter.java:139)
	at org.springframework.web.socket.server.standard.ServerEndpointExporter.afterSingletonsInstantiated(ServerEndpointExporter.java:111)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:866)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:877)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:549)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:775)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:316)
	at org.springframework.boot.test.context.SpringBootContextLoader.loadContext(SpringBootContextLoader.java:127)
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContextInternal(DefaultCacheAwareContextLoaderDelegate.java:99)
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:117)
	... 49 more
```

I there any way to disable adding a Endpoint to the Servlet for my tests?

**Comment by oliemansm** [comment] 2019-04-05 19:11
Have you tried using GraphqlTestTemplate from the test starter?

Groeten,
Michiel

________________________________
Van: Niclas <notifications@github.com>
Verzonden: vrijdag, april 5, 2019 8:36 PM
Aan: graphql-java-kickstart/graphql-spring-boot
CC: Subscribed
Onderwerp: [graphql-java-kickstart/graphql-spring-boot] Testing with spring MocMVC (#230)


I want to test graphql and integrate it into my REST-Spring-Boot-Application.
Currently I'm getting errors because all my tests are using MocMVC, but as I found out, this graphql lib needs a real Servlet, not the MocMvc one.

Caused by: java.lang.UnsupportedOperationException: MockServerContainer does not support addEndpoint(ServerEndpointConfig)
        at org.springframework.test.context.web.socket.MockServerContainer.addEndpoint(MockServerContainer.java:131)
        at org.springframework.web.socket.server.standard.ServerEndpointExporter.registerEndpoint(ServerEndpointExporter.java:169)
        at org.springframework.web.socket.server.standard.ServerEndpointExporter.registerEndpoints(ServerEndpointExporter.java:139)
        at org.springframework.web.socket.server.standard.ServerEndpointExporter.afterSingletonsInstantiated(ServerEndpointExporter.java:111)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:866)
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:877)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:549)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:775)
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:316)
        at org.springframework.boot.test.context.SpringBootContextLoader.loadContext(SpringBootContextLoader.java:127)
        at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContextInternal(DefaultCacheAwareContextLoaderDelegate.java:99)
        at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:117)
        ... 49 more


I there any way to disable adding a Endpoint to the Servlet for my tests?

**Comment by nidomiro** [comment] 2019-04-05 19:32
Thanks for your Reply :)

As far as I understand GraphqlTestTemplate is for testing Graphql. But I'm far away from that.
Just adding `compile "com.graphql-java-kickstart:graphql-spring-boot-starter:${graphQlVersion}` to my gradle dependencies breaks all my Tests with the exception above.

My search revealed that this error occurs because this lib wants to add a endpoint to the Servlet, but in case of the MocMvc-Servlet this operation results in a Exception.

If I use `@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)` instead of `@SpringBootTest` my Tests are working, except for the Controller-tests, because `MockMvc` is not available via `@Autowire`.
Because of this I would have to rewrite all my Controller-tests - and that is something I want to avoid.

If there is a way to disable the automatic registration of the GraphQl servlet for some Tests I could run all my Tests as usual. Maybe even the other way around, enable registration specifically for the GraphQl Tests.

I hope this describes my problem better ;)

Best regards,
Niclas

**Comment by oliemansm** [comment] 2019-04-05 19:44
Ah, that explains it better :)

One possibly quick workaround that comes to mind is to add the exclude parameter on SpringBootTest annotation to exclude the graphqlwebautoconfiguration.

Groeten,
Michiel

________________________________
Van: Niclas <notifications@github.com>
Verzonden: vrijdag, april 5, 2019 9:32 PM
Aan: graphql-java-kickstart/graphql-spring-boot
CC: Michiel Oliemans; Comment
Onderwerp: Re: [graphql-java-kickstart/graphql-spring-boot] Testing with spring MocMVC (#230)


Thanks for your Reply :)

As far as I understand GraphqlTestTemplate is for testing Graphql. But I'm far away from that.
Just adding compile "com.graphql-java-kickstart:graphql-spring-boot-starter:${graphQlVersion} to my gradle dependencies breaks all my Tests with the exception above.

My search revealed that this error occurs because this lib wants to add a endpoint to the Servlet, but in case of the MocMvc-Servlet this operation results in a Exception.

If I use @SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT) instead of @SpringBootTest my Tests are working, except for the Controller-tests, because MockMvc is not available via @Autowire.
Because of this I would have to rewrite all my Controller-tests - and that is something I want to avoid.

If there is a way to disable the automatic registration of the GraphQl servlet for some Tests I could run all my Tests as usual. Maybe even the other way around, enable registration specifically for the GraphQl Tests.

I hope this describes my problem better ;)

Best regards,
Niclas

**Comment by nidomiro** [comment] 2019-04-05 20:28
Thanks, this seems to work, all tests are green again - now I can work on my GraphQl Test Setup :)
```
@TestPropertySource(
    properties = [
        "spring.autoconfigure.exclude=com.oembedler.moon.graphql.boot.GraphQLWebAutoConfiguration",
        "spring.autoconfigure.exclude=com.oembedler.moon.graphql.boot.GraphQLWebsocketAutoConfiguration"
    ]
)
```
Best regards,
Niclas

**Comment by oliemansm** [comment] 2019-06-19 15:53
Closing this issue since it seems to be resolved for you. If not, feel free to re-open it of course.

**Closed by oliemansm** 2019-06-19 15:53 UTC

**Comment by Marx2** [comment] 2020-04-14 11:21
Current fix:
```
properties = { "spring.autoconfigure.exclude=graphql.kickstart.spring.web.boot.GraphQLWebAutoConfiguration",
"spring.autoconfigure.exclude=graphql.kickstart.spring.web.boot.GraphQLWebsocketAutoConfiguration" })
```
