### ISSUE TITLE
We also need a webflux version

### ISSUE THREAD

**Issue by apollo7733** [graphql-java-kickstart/graphql-spring-boot#291] opened 2019-10-27 00:43 UTC
This is a good project.I've used it on several projects.We also need a webflux version.

**Comment by gklijs** [comment] 2019-11-09 12:22
What do you mean? It can already by used with webflux, you kind of need to to support subscriptions.

**Comment by apollo7733** [comment] 2019-11-10 02:30
When you only choose
  org.springframework.boot:spring-boot-starter-webflux
Spring tool suite will start Netty server on port(s): 8080
But when you add graphql-spring-boot-starter
Spring tool suite will start Tomcat server on port(s): 8080

because graphql-spring-boot-starter use servlet and  Reactive Streams base on Servlet 3.1 non-blocking I/O to Reactive Streams bridge.

**Comment by oliemansm** [comment] 2019-11-18 11:49
Duplicate of #265, please follow that thread instead.

**Closed by oliemansm** 2019-11-18 11:49 UTC
