### ISSUE TITLE
Add support for graphql-java-annotations?

### ISSUE THREAD

**Issue by exports** [graphql-java-kickstart/graphql-spring-boot#5] opened 2017-04-25 04:21 UTC
Currently this project can discover schema automatically defined by graphql-java-tools, it would be good if we can support graphql-java-annotations too.

**Comment by apottere** [comment] 2017-05-17 15:00
Do you happen to have ideas about how this could work?  I don't use annotations so I'm not sure if I'm the right person to implement this.

**Comment by apottere** [comment] 2017-06-13 14:24
@bbakerman do you have any input on how this might work?

**Comment by mushketyk** [comment] 2017-07-24 09:03
Hi @exports 

I suggest to read discussion in #20. I've described a way to access Spring beans from `graphql-annotations` data fetchers and @apottere is working on making it possible in `graphql-spring-boot`.

**Comment by tirtzab** [comment] 2018-03-21 01:24
I'm working on integrating graphql-java-annotations and graphql-spring-boot.  I believe I have a solution but am running into an issue since both projects use the same package name- graphql.execution.  It picks up the class from the wrong project since both projects share identical package names and class names.  Any reason not to change the package name?

**Comment by seetharamani** [comment] 2018-07-15 20:52
Instead of using <code>graphql-spring-boot</code>
 I have used <code>graphql-java-servlet</code> to work along with <code>graphql-java-annotations</code>, as suggested in the issue #20. I am able to start my application and access the graphql schema in the url <code>/graphql/schema.json</code>. But when I try to execute my any query or mutation, I am getting below exception.

```
Caused by: java.lang.NoSuchFieldException: newAuthor
	at java.lang.Class.getDeclaredField(Class.java:2070) ~[na:1.8.0_162]
	at graphql.annotations.dataFetchers.MethodDataFetcher.getFieldValue(MethodDataFetcher.java:139) ~[graphql-java-annotations-5.3.jar!/:na]
	at graphql.annotations.dataFetchers.MethodDataFetcher.get(MethodDataFetcher.java:61) ~[graphql-java-annotations-5.3.jar!/:na]
```

 Schema itself looks good with my <code>Query</code> type listing <code>newAuthor</code> as a field. But its not resolving from the <code>Query GraphQLObjectType</code>

Below is how I defined my Query

``` package com.dominos.ecommerce.graphql.resolver;

import com.coxautodev.graphql.tools.GraphQLQueryResolver;
import graphql.annotations.annotationTypes.GraphQLField;
import graphql.annotations.annotationTypes.GraphQLName;
import graphql.annotations.annotationTypes.GraphQLNonNull;
import lombok.AllArgsConstructor;
import org.springframework.stereotype.Component;

@Component
@AllArgsConstructor
@GraphQLName("query")
public class Query implements GraphQLQueryResolver {

    private final AuthorRepository authorRepository;
    private final BookRepository bookRepository;

    @GraphQLField
    public Iterable<Book> findAllBooks() {
        return bookRepository.findAll();
    }

    @GraphQLField
    public Iterable<Author> findAllAuthors() {
        return authorRepository.findAll();
    }

    @GraphQLField
    public long countBooks() {
        return bookRepository.count();
    }

    @GraphQLField
    public long countAuthors() {
        return authorRepository.count();
    }
}
```

**Comment by benneq** [comment] 2018-08-20 11:17
I guess the problem is, that graphql-java-annotations inspects the class itself, but not the instantiated singleton object.
I created an issue here ( https://github.com/graphql-java/graphql-java-annotations/issues/187 ), asking to allow inspecting objects, instead of classes only.

**Comment by oliemansm** [comment] 2020-09-06 07:58
This has been added to 7.2.0 thanks to @BlasiusSecundus

**Closed by oliemansm** 2020-09-06 07:58 UTC
Labels: help wanted
